channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - jupyterlab
  - pymc
  - jax
  - cuda-nvcc
  - arviz 
  - git 
  - pip
  - "r-essentials"
  - r-raster
  - r-rgdal
  - pip:
    - ecoscope
    - pyarrow