Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE);
options(timeout=30000);
# install.packages(c("moveHMM"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("mclust"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("geoR"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("adehabitatlt"), dependencies=TRUE, repos="http://cran.rstudio.com/", Ncpus=5);
# install.packages(c("rgdal", "lifecycle"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("lifecycle"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("vctrs"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("ggmap"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("geosphere"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("numDeriv"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("RcppArmadillo"), dependencies=TRUE, repos="http://cran.rstudio.com/");
install.packages(c("devtools"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("uuid"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("igraph"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("vroom"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("raster>=3.1-5"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("stringi"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("rgeos"), dependencies=TRUE, repos="http://cran.rstudio.com/");
# install.packages(c("sp"), dependencies=TRUE, repos="http://cran.rstudio.com/");
devtools::install_version(c("INLA"), version = "22.03.09", dependencies=TRUE, repos=c("https://inla.r-inla-download.org/R/testing"));
devtools::install_github(c("BastilleRousseau/moveNT@master"), dependencies=TRUE);
# devtools::install_github("inbo/inlatools", dependencies=TRUE);